version: '3'

services:
  # Django web application
  auto_company:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:80"
    volumes:
      - .:/app
    ports:
      - "80:80"
    depends_on:
      - sparts_hub_db

  # PostgreSQL database
  sparts_hub_db:
    image: postgres:latest
    environment:
      POSTGRES_DB: car_spare_parts
      POSTGRES_USER: nihal
      POSTGRES_PASSWORD: ncr5630
    ports:
      - "5432:5432"
