# Generated by Django 5.0.1 on 2024-02-03 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_sparts_hub', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermaster',
            name='invoiceCode',
            field=models.CharField(editable=False, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='productCord',
            field=models.CharField(editable=False, max_length=20, unique=True),
        ),
    ]
