# Generated by Django 5.0.1 on 2024-02-03 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_sparts_hub', '0002_alter_ordermaster_invoicecode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sellingPrice',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
