# Generated by Django 5.0.1 on 2024-02-03 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_sparts_hub', '0003_alter_product_sellingprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productName',
            field=models.CharField(max_length=300, unique=True),
        ),
    ]
