# Generated by Django 5.0.1 on 2024-02-03 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_sparts_hub', '0004_alter_product_productname'),
        ('customer', '0002_alter_customer_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordersdetails',
            name='OrderMasterId',
        ),
        migrations.RemoveField(
            model_name='ordersdetails',
            name='productId',
        ),
        migrations.AlterField(
            model_name='masterstock',
            name='totalSelling',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='This value is for selling items only', max_digits=10),
        ),
        migrations.AlterUniqueTogether(
            name='masterstock',
            unique_together={('category', 'product')},
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_date', models.DateTimeField(blank=True, null=True)),
                ('is_ordered', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='car_sparts_hub.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_sparts_hub.product')),
            ],
        ),
        migrations.DeleteModel(
            name='OrderMaster',
        ),
        migrations.DeleteModel(
            name='ordersDetails',
        ),
    ]
